import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const uiHtml = readFileSync(resolve(__dirname, '../../ui/dist/index.html'), 'utf-8')
const output = `// Auto-generated by embed-ui.mjs - do not edit\nexport const UI_HTML: string = ${JSON.stringify(uiHtml)}\n`
writeFileSync(resolve(__dirname, '../src/ui/html.ts'), output)
console.log('UI HTML embedded successfully')
